// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleHintAction
        {
            get
            {
                return SteamVR_Actions.default_ToggleHintAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScreenFartherAction
        {
            get
            {
                return SteamVR_Actions.default_ScreenFartherAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScreenNearerAction
        {
            get
            {
                return SteamVR_Actions.default_ScreenNearerAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScreenBiggerAction
        {
            get
            {
                return SteamVR_Actions.default_ScreenBiggerAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScreenSmallerAction
        {
            get
            {
                return SteamVR_Actions.default_ScreenSmallerAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScreenHigherAction
        {
            get
            {
                return SteamVR_Actions.default_ScreenHigherAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScreenLowerAction
        {
            get
            {
                return SteamVR_Actions.default_ScreenLowerAction;
            }
        }
    }
}
