// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_default_ToggleHintAction;
        
        private static SteamVR_Action_Boolean p_default_ScreenFartherAction;
        
        private static SteamVR_Action_Boolean p_default_ScreenNearerAction;
        
        private static SteamVR_Action_Boolean p_default_ScreenBiggerAction;
        
        private static SteamVR_Action_Boolean p_default_ScreenSmallerAction;
        
        private static SteamVR_Action_Boolean p_default_ScreenHigherAction;
        
        private static SteamVR_Action_Boolean p_default_ScreenLowerAction;
        
        private static SteamVR_Action_Boolean p_default_RecenterAction;
        
        private static SteamVR_Action_Boolean p_default_HideFloorAction;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Boolean p_default_GrabGrip;
        
        private static SteamVR_Action_Boolean p_default_ToggleSharpeningAction;
        
        private static SteamVR_Action_Boolean p_default_ResetAllAction;
        
        private static SteamVR_Action_Boolean p_default_CurveScreen;
        
        private static SteamVR_Action_Boolean p_default_FlattenScreen;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy <SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy <SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy <SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ToggleHintAction
        {
            get
            {
                return SteamVR_Actions.p_default_ToggleHintAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ScreenFartherAction
        {
            get
            {
                return SteamVR_Actions.p_default_ScreenFartherAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ScreenNearerAction
        {
            get
            {
                return SteamVR_Actions.p_default_ScreenNearerAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ScreenBiggerAction
        {
            get
            {
                return SteamVR_Actions.p_default_ScreenBiggerAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ScreenSmallerAction
        {
            get
            {
                return SteamVR_Actions.p_default_ScreenSmallerAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ScreenHigherAction
        {
            get
            {
                return SteamVR_Actions.p_default_ScreenHigherAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ScreenLowerAction
        {
            get
            {
                return SteamVR_Actions.p_default_ScreenLowerAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RecenterAction
        {
            get
            {
                return SteamVR_Actions.p_default_RecenterAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HideFloorAction
        {
            get
            {
                return SteamVR_Actions.p_default_HideFloorAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabGrip.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ToggleSharpeningAction
        {
            get
            {
                return SteamVR_Actions.p_default_ToggleSharpeningAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ResetAllAction
        {
            get
            {
                return SteamVR_Actions.p_default_ResetAllAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_CurveScreen
        {
            get
            {
                return SteamVR_Actions.p_default_CurveScreen.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_FlattenScreen
        {
            get
            {
                return SteamVR_Actions.p_default_FlattenScreen.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy <SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[]
            {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_ToggleHintAction,
                    SteamVR_Actions.default_ScreenFartherAction,
                    SteamVR_Actions.default_ScreenNearerAction,
                    SteamVR_Actions.default_ScreenBiggerAction,
                    SteamVR_Actions.default_ScreenSmallerAction,
                    SteamVR_Actions.default_ScreenHigherAction,
                    SteamVR_Actions.default_ScreenLowerAction,
                    SteamVR_Actions.default_RecenterAction,
                    SteamVR_Actions.default_HideFloorAction,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_ToggleSharpeningAction,
                    SteamVR_Actions.default_ResetAllAction,
                    SteamVR_Actions.default_CurveScreen,
                    SteamVR_Actions.default_FlattenScreen,
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_ToggleHintAction,
                    SteamVR_Actions.default_ScreenFartherAction,
                    SteamVR_Actions.default_ScreenNearerAction,
                    SteamVR_Actions.default_ScreenBiggerAction,
                    SteamVR_Actions.default_ScreenSmallerAction,
                    SteamVR_Actions.default_ScreenHigherAction,
                    SteamVR_Actions.default_ScreenLowerAction,
                    SteamVR_Actions.default_RecenterAction,
                    SteamVR_Actions.default_HideFloorAction,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_ToggleSharpeningAction,
                    SteamVR_Actions.default_ResetAllAction,
                    SteamVR_Actions.default_CurveScreen,
                    SteamVR_Actions.default_FlattenScreen};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[]
            {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[]
            {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[]
            {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[]
            {
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_ToggleHintAction,
                    SteamVR_Actions.default_ScreenFartherAction,
                    SteamVR_Actions.default_ScreenNearerAction,
                    SteamVR_Actions.default_ScreenBiggerAction,
                    SteamVR_Actions.default_ScreenSmallerAction,
                    SteamVR_Actions.default_ScreenHigherAction,
                    SteamVR_Actions.default_ScreenLowerAction,
                    SteamVR_Actions.default_RecenterAction,
                    SteamVR_Actions.default_HideFloorAction,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_ToggleSharpeningAction,
                    SteamVR_Actions.default_ResetAllAction,
                    SteamVR_Actions.default_CurveScreen,
                    SteamVR_Actions.default_FlattenScreen};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[]
            {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_ToggleHintAction,
                    SteamVR_Actions.default_ScreenFartherAction,
                    SteamVR_Actions.default_ScreenNearerAction,
                    SteamVR_Actions.default_ScreenBiggerAction,
                    SteamVR_Actions.default_ScreenSmallerAction,
                    SteamVR_Actions.default_ScreenHigherAction,
                    SteamVR_Actions.default_ScreenLowerAction,
                    SteamVR_Actions.default_RecenterAction,
                    SteamVR_Actions.default_HideFloorAction,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_ToggleSharpeningAction,
                    SteamVR_Actions.default_ResetAllAction,
                    SteamVR_Actions.default_CurveScreen,
                    SteamVR_Actions.default_FlattenScreen};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create <SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create <SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create <SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_ToggleHintAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/ToggleHintAction")));
            SteamVR_Actions.p_default_ScreenFartherAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/ScreenFartherAction")));
            SteamVR_Actions.p_default_ScreenNearerAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/ScreenNearerAction")));
            SteamVR_Actions.p_default_ScreenBiggerAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/ScreenBiggerAction")));
            SteamVR_Actions.p_default_ScreenSmallerAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/ScreenSmallerAction")));
            SteamVR_Actions.p_default_ScreenHigherAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/ScreenHigherAction")));
            SteamVR_Actions.p_default_ScreenLowerAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/ScreenLowerAction")));
            SteamVR_Actions.p_default_RecenterAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/RecenterAction")));
            SteamVR_Actions.p_default_HideFloorAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/HideFloorAction")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            SteamVR_Actions.p_default_ToggleSharpeningAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/ToggleSharpeningAction")));
            SteamVR_Actions.p_default_ResetAllAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/ResetAllAction")));
            SteamVR_Actions.p_default_CurveScreen = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/CurveScreen")));
            SteamVR_Actions.p_default_FlattenScreen = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/FlattenScreen")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create <SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
        }
    }
}
